all:
  children:
    k3s_cluster:
      hosts:
        k3s-master-01:
          ansible_host: 192.0.2.100 # Replace with Terraform output k3s_cluster_public_ip
          ansible_user: opc
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
