apiVersion: v1
kind: ConfigMap
metadata:
  name: enterprise-config
  namespace: enterprise-devops
data:
  NODE_ENV: "production"
  PORT: "5000"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "enterprise_db"
  CORS_ORIGIN: "*"
  NEXT_PUBLIC_BACKEND_URL: "http://backend-service:5000/healthz"
