apiVersion: v1
kind: Secret
metadata:
  name: enterprise-secrets
  namespace: enterprise-devops
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "enterprise-secure-postgres-password-prod"
  JWT_SECRET: "enterprise-super-secure-production-jwt-key-998822"
